name: "LiveSafe kubectl"
description: "Interacts with kubernetes clusters calling kubectl commands. Integrates support for AWS EKS."
branding:
  icon: 'anchor'  
  color: 'blue'
inputs:
  args:
    description: "Arguments passed to the kubectl command"
    required: true
outputs:
  result:
    description: "Output of the kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
