name: "LiveSafe kubectl apply"
description: "Interacts with kubernetes clusters or removing kubectl resources. Integrates support for AWS EKS."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  command:
    description: "Command passed to kubectl"
    required: true
    default: 'apply'
  manifest:
    description: 'Path to the Kubernetes manifest file'
    required: true
  namespace:
    description: 'If present, the namespace scope for this action. If not specified, it will use the current context'
    required: false
    default:
outputs:
  result:
    description: "Output of the kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.manifest }}
    - ${{ inputs.namespace }}